---
ci:
  skip: [poetry->requirements.txt, poetry->requirements-dev.txt]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
  - repo: https://github.com/asottile/dead
    rev: v1.4.0
    hooks:
      - id: dead
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.1
    hooks:
      - id: dockerfile_lint
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.1
    hooks:
      - id: docker-compose-check
      - id: hadolint
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.29.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
      - id: detect-secrets
  - repo: local
    hooks:
      - id: poetry->requirements.txt
        name: poetry->requirements.txt
        entry: bash -c 'diff -q -s <(poetry export --without-hashes -f requirements.txt) <(cat requirements.txt)'  # yamllint disable-line
        language: system
        types: [python]
        pass_filenames: false
  - repo: local
    hooks:
      - id: poetry->requirements-dev.txt
        name: poetry->requirements-dev.txt
        entry: bash -c 'diff -q -s <(poetry export --without-hashes -f requirements.txt --dev) <(cat requirements-dev.txt)'  # yamllint disable-line
        language: system
        types: [python]
        pass_filenames: false
