site_name: Knex Docs
repo_url: https://github.com/clay584/knex/
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - About: about.md
  - API Reference:
      - Parsers: parsers-reference.md
theme:
  name: material
  palette:
    - scheme: default
      accent: orange
      primary: deep orange
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      accent: orange
      primary: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
# highlightjs: true
plugins:
  - search
  - mkdocstrings:
      watch:
        - knex
