---
name: Publish Docs to GH Pages
on:  # yamllint disable-line
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install GCC
        uses: egor-tensin/setup-gcc@v1
      - uses: actions/checkout@v2
      - name: Deploy Docs to GH Pages
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.23
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
