---
name: Pytest
on: [push, pull_request] # yamllint disable-line rule:truthy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Poetry Install
        uses: knowsuchagency/poetry-install@v2
      - name: pytest
        run: poetry run pytest -v
      - name: Run coverage
        run: poetry run coverage run
      - name: Run coverage xml
        run: poetry run coverage xml -o cobertura.xml
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: cobertura.xml
