---
name: Pytest
on: [push, pull_request] # yamllint disable-line rule:truthy
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Poetry Install
        uses: knowsuchagency/poetry-install@v2
      - name: pytest
        run: poetry run pytest -v
